project:
  type: website
  output-dir: docs
  resources:
    - running.mp4

website:
  title: "Arman Soleimani"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: running.qmd
        text: Running

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
